---
- hosts: localhost
  roles: 
    - role: network
      interfaces_ether_interfaces: 
       - device: eth0
         bootproto: static
         address: 192.168.0.69
         netmask: 255.255.255.0
         gateway: 192.168.0.254
         dnsservers: ["8.8.8.8", "8.8.4.4"]
         dnssearch: example.com
       - device: eth0.88
         bootproto: static
         address: 192.168.88.69 
         netmask: 255.255.255.0
         vlan: yes
       - device: eth0:0
         bootproto: static
         address: 192.168.0.68 
         netmask: 255.255.255.0
      interfaces_bridge_interfaces:
       -  device: br0
          type: bridge
          bootproto: static
          address: 192.168.0.29
          netmask: 255.255.255.0
          ports: [eth1, eth2]
      interfaces_bond_interfaces:
        - device: bond0
          bootproto: dhcp
          bond_mode: 802.3ad
          bond_miimon: 100
          bond_slaves: [eth3, eth4]
