---

- include: 'debian.yml'
  when: ansible_os_family == 'Debian'

- include: 'redhat.yml'
  when: ansible_os_family == 'RedHat'

- name: load the 802.1q (vlan) module
  modprobe: name=8021q state=present

- include: 'ethernet_configuration.yml'
  when: interfaces_ether_interfaces is defined
  tags: configuration

- include: 'bridge_configuration.yml'
  when: interfaces_bridge_interfaces is defined
  tags: configuration

- include: 'bond_configuration.yml'
  when: interfaces_bond_interfaces is defined
  tags: configuration

- name: Bring up/down ether interfaces
  shell: 'ifdown {{ item.item.device }}; ifup {{ item.item.device }}'
  with_items: '{{ ether_result.results }}'
  when: ether_result is defined and item.changed
