---

- include: 'debian.yml'
  when: ansible_os_family == 'Debian'

- include: 'redhat.yml'
  when: ansible_os_family == 'RedHat'

- name: load the 802.1q (vlan) module
  modprobe: name=8021q state=present

- include: 'bridge_configuration.yml'
  when: interfaces_bridge_interfaces is defined
  tags: configuration

- include: 'bond_configuration.yml'
  when: interfaces_bond_interfaces is defined
  tags: configuration

- include: 'team_configuration.yml'
  when: interfaces_team_interfaces is defined
  tags: configuration

- include: 'ethernet_configuration.yml'
  when: interfaces_ether_interfaces is defined
  tags: configuration
