---

- name: Create the network configuration file for team devices
  template:
    src: 'team_{{ ansible_os_family }}.j2'
    dest: '{{ interfaces_net_path[ansible_os_family] }}/ifcfg-{{ item.device }}'
  with_items: '{{ interfaces_team_interfaces }}'
  register: team_result

- name: Write configuration files for route configuration
  template:
    src: 'route_{{ ansible_os_family }}.j2'
    dest: '{{ interfaces_net_path[ansible_os_family] }}/route-{{ item.device }}'
  with_items: '{{ interfaces_team_interfaces }}'
  when: item.route is defined and ansible_os_family == 'RedHat'

- shell: 'ifdown {{ item.item.device }}; ifup {{ item.item.device }}'
  with_items: '{{ team_result.results }}'
  when: team_result is defined and item.changed

- name: Create the network configuration file for slave in the team devices
  template:
    src: 'team_slave_{{ ansible_os_family }}.j2'
    dest: '{{ interfaces_net_path[ansible_os_family] }}/ifcfg-{{ item.1 }}'
  with_subelements:
   - '{{ interfaces_team_interfaces }}'
   - team_slaves
  register: team_port_result

- shell: 'ifdown {{ item.item.1 }}; ifup {{ item.item.1 }}'
  with_items: '{{ team_port_result.results }}'
  when: team_port_result is defined and item.changed

- shell: 'ifdown {{ item.item.device }}; ifup {{ item.item.device }}'
  with_items: '{{ team_result.results }}'
  when: team_result is defined and item.changed and ansible_os_family == 'RedHat'
