- name: install docker prereqs
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
    state: installed
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: add docker repo key (deb based)
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: add docker repo (deb based)
  apt_repository:
    repo: "deb  https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }} stable"
    state: present
    filename: docker-ce
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install docker! (deb based)
  apt:
    name: "{{ docker_packages }}"
    update_cache: yes
    state: installed
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  vars:
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: configure http proxy for docker
  blockinfile:
    path: /etc/systemd/system/docker.service.d/http-proxy.conf
    block: |
      [Service]
      Environment="{{ httpsproxy }}"
    create: yes
  notify:
    - poke systemd
